# -*- coding: utf-8 -*-
"""STREAMLIT_SHOPPING.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qJ8hFky278AzY4JJgIHOCOimzS5TZYZP

**STREAMLIT EXECUTION**
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile shopping.py
# 
# import streamlit as st
# st.set_page_config(page_title="Shopper Spectrum", layout="centered")
# 
# import pandas as pd
# import joblib
# from sklearn.preprocessing import StandardScaler
# from sklearn.cluster import KMeans
# from scipy import sparse
# import requests
# import os
# 
# # ----------------------------
# # 📦 Load all saved models/data
# # ----------------------------
# scaler = joblib.load(r"/content/rfm_scaler.pkl")
# kmeans = joblib.load(r"/content/kmeans_model.pkl")
# product_lookup = joblib.load(r"/content/product_lookup.pkl")
# rfm = pd.read_csv(r"/content/rfm_segments.csv")
# 
# # ✅ Download & Load product similarity from Google Drive if not present
# @st.cache_resource
# def load_product_similarity():
#     file_path = r"/content/product_similarity.pkl"
#     if not os.path.exists(file_path):
#         st.info("📦 Downloading product similarity file...")
#         url = "https://drive.google.com/uc?export=download&id=1YWXrrR3e8UT3oHEJqAXOSTwPMyJv4pkM"
#         response = requests.get(url)
#         with open(file_path, 'wb') as f:
#             f.write(response.content)
#     return joblib.load(file_path)
# 
# product_similarity = load_product_similarity()
# 
# # ----------------------------
# # 🧠 Predict Customer Segment
# # ----------------------------
# def predict_cluster(r, f, m):
#     X_scaled = scaler.transform([[r, f, m]])
#     cluster = kmeans.predict(X_scaled)[0]
#     return cluster
# 
# def cluster_to_label(cluster):
#     label_map = {
#         0: "Regular",
#         1: "At-Risk",
#         2: "High-Value",
#         3: "High-Value",
#         4: "High-Value"
#     }
#     return label_map.get(cluster, "Unknown")
#     # ----------------------------
# # 🔍 Recommend Similar Products
# # ----------------------------
# def get_similar_products(product_code, n=5):
#     if product_code not in product_similarity.columns:
#         return []
#     similarities = product_similarity[product_code].sort_values(ascending=False)
#     top_similar = similarities.drop(product_code).head(n)
#     return [(code, product_lookup.get(code, "Unknown")) for code in top_similar.index]
# 
# # ----------------------------
# # 🎨 Streamlit App Layout
# # ----------------------------
# st.title("🛒 Shopper Spectrum: Customer Segmentation & Recommendations")
# 
# tab1, tab2 = st.tabs(["🔍 Product Recommendation", "👤 Customer Segment Prediction"])
# 
# # ----------------------------
# # 📦 Tab 1: Product Recommendation
# # ----------------------------
# with tab1:
#     st.subheader("🔍 Recommend Similar Products")
# 
#     user_input = st.text_input("Enter product name or StockCode (e.g., 'heart' or '85123A')").strip().lower()
#     matched_code = None
# 
#     if user_input:
#         if user_input.upper() in product_lookup:
#             matched_code = user_input.upper()
#         else:
#             matches = [code for code, name in product_lookup.items() if user_input in name.lower()]
#             if matches:
#                 matched_code = matches[0]
# 
#     if st.button("Get Recommendations"):
#         if matched_code:
#             recs = get_similar_products(matched_code)
#             if recs:
#                 st.success(f"Top 5 Recommended Products for **{matched_code}** - *{product_lookup.get(matched_code)}*:")
#                 for code, name in recs:
#                     st.markdown(f"- **{code}**: {name}")
#             else:
#                 st.warning("No recommendations found.")
#         else:
#             st.error("No matching product found. Please try another name or code.")
# 
# # ----------------------------
# # 👤 Tab 2: Customer Segment Prediction
# # ----------------------------
# with tab2:
#     st.subheader("👤 Predict Customer Segment")
# 
#     r = st.number_input("Recency (days since last purchase)", min_value=0, value=30)
#     f = st.number_input("Frequency (number of purchases)", min_value=0, value=5)
#     m = st.number_input("Monetary (total spend in ₹)", min_value=0.0, value=1000.0)
# 
#     if st.button("Predict Segment"):
#         cluster = predict_cluster(r, f, m)
#         label = cluster_to_label(cluster)
#         st.success(f"This customer belongs to the **{label}** segment.")
# 
# # ----------------------------
# # ✅ Footer
# # ----------------------------
# st.markdown("---")
# st.markdown("Made with ❤️ using Streamlit")
# 
# 
#

!wget -q -O - ipv4.icanhazip.com

! streamlit run shopping.py & npx localtunnel --port 8501

!wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
!dpkg -i cloudflared-linux-amd64.deb

!streamlit run shopping.py &>/content/logs.txt &

!cloudflared tunnel --url http://localhost:8501